name: Windows CI (msvc)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release, Debug]
        platform: [x64, Win32]
    steps:
    - uses: actions/checkout@v2
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: 1.3.211.0
        cache: true
    - name: Build vkQuake
      run: |
        $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        $msbuild = & "$vswhere" -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe | select-object -first 1
        $options = @( `
          '-property:Configuration=${{ matrix.configuration }}', `
          '-property:Platform=${{ matrix.platform }}', `
          '-maxcpucount', `
          '-verbosity:minimal' `
        )
        & $msbuild Windows\VisualStudio\vkquake.sln $options
        if (-not $?) { throw "Build failed" }
    - name: Upload vkQuake
      uses: actions/upload-artifact@v3
      with:
        name: vkQuake archive
        path: |
            Windows\VisualStudio\Build-vkQuake\**\*.exe
            Windows\VisualStudio\Build-vkQuake\**\*.dll
